export type MockPatent = {
  id: string;
  patent_number: string;
  title: string;
  abstract: string;
  applicant: string;
  filing_date: string;
  status: 'granted' | 'pending' | 'rejected';
  classification: string;
  citations_count: number;
  similarity_score: number;
  related_patents: string[];
  category: string;
};

export const mockPatents: MockPatent[] = [
  {
    id: 'p1',
    patent_number: 'US-10421873',
    title: 'Neural Network-Based Image Recognition System',
    abstract: 'A deep learning architecture for real-time image classification using convolutional neural networks with attention mechanisms for enhanced accuracy in object detection tasks.',
    applicant: 'DeepVision Technologies',
    filing_date: '2023-01-15',
    status: 'granted',
    classification: 'G06N-3/04',
    citations_count: 142,
    similarity_score: 0.94,
    related_patents: ['p2', 'p5', 'p8'],
    category: 'AI & Machine Learning',
  },
  {
    id: 'p2',
    patent_number: 'US-10532198',
    title: 'Transformer Architecture for Natural Language Processing',
    abstract: 'An improved transformer model with multi-head attention mechanisms optimized for long-context language understanding and generation tasks.',
    applicant: 'Cognitive Systems Inc.',
    filing_date: '2023-03-22',
    status: 'granted',
    classification: 'G06N-3/08',
    citations_count: 218,
    similarity_score: 0.91,
    related_patents: ['p1', 'p3', 'p7'],
    category: 'AI & Machine Learning',
  },
  {
    id: 'p3',
    patent_number: 'US-10678432',
    title: 'Reinforcement Learning for Autonomous Decision Systems',
    abstract: 'A reinforcement learning framework enabling autonomous agents to make optimal decisions in complex, dynamic environments using policy gradient methods.',
    applicant: 'AutoMind Robotics',
    filing_date: '2023-05-10',
    status: 'pending',
    classification: 'G06N-3/00',
    citations_count: 67,
    similarity_score: 0.88,
    related_patents: ['p2', 'p4'],
    category: 'AI & Machine Learning',
  },
  {
    id: 'p4',
    patent_number: 'US-10781234',
    title: 'Quantum-Enhanced Optimization Algorithm',
    abstract: 'A hybrid quantum-classical algorithm for solving combinatorial optimization problems with exponential speedup over classical methods.',
    applicant: 'Quantum Labs',
    filing_date: '2023-02-28',
    status: 'granted',
    classification: 'G06N-10/00',
    citations_count: 95,
    similarity_score: 0.82,
    related_patents: ['p3', 'p6'],
    category: 'Quantum Computing',
  },
  {
    id: 'p5',
    patent_number: 'US-10893456',
    title: 'Edge Computing Architecture for IoT Devices',
    abstract: 'A distributed edge computing framework for processing IoT sensor data with minimal latency using federated learning across heterogeneous devices.',
    applicant: 'EdgeFlow Systems',
    filing_date: '2023-04-18',
    status: 'granted',
    classification: 'H04L-67/10',
    citations_count: 78,
    similarity_score: 0.79,
    related_patents: ['p1', 'p9'],
    category: 'IoT & Edge Computing',
  },
  {
    id: 'p6',
    patent_number: 'US-10956789',
    title: 'Blockchain-Based Supply Chain Verification',
    abstract: 'A decentralized ledger system for supply chain transparency using smart contracts and cryptographic proofs for immutable audit trails.',
    applicant: 'ChainVerify Solutions',
    filing_date: '2023-06-05',
    status: 'pending',
    classification: 'H04L-9/06',
    citations_count: 54,
    similarity_score: 0.75,
    related_patents: ['p4', 'p10'],
    category: 'Blockchain',
  },
  {
    id: 'p7',
    patent_number: 'US-11023456',
    title: 'Generative Adversarial Network for Synthetic Data',
    abstract: 'A GAN-based framework for generating high-fidelity synthetic training data with differential privacy guarantees for sensitive domains.',
    applicant: 'SynthData AI',
    filing_date: '2023-07-12',
    status: 'granted',
    classification: 'G06N-3/04',
    citations_count: 112,
    similarity_score: 0.87,
    related_patents: ['p2', 'p8'],
    category: 'AI & Machine Learning',
  },
  {
    id: 'p8',
    patent_number: 'US-11156789',
    title: 'Federated Learning Privacy Framework',
    abstract: 'A privacy-preserving federated learning system with secure aggregation and homomorphic encryption for collaborative model training.',
    applicant: 'PrivacyFirst AI',
    filing_date: '2023-08-20',
    status: 'pending',
    classification: 'G06N-20/00',
    citations_count: 43,
    similarity_score: 0.83,
    related_patents: ['p1', 'p7', 'p9'],
    category: 'AI & Machine Learning',
  },
  {
    id: 'p9',
    patent_number: 'US-11234567',
    title: '5G Network Slice Orchestration System',
    abstract: 'An intelligent orchestration platform for dynamic 5G network slicing with ML-driven resource allocation and QoS guarantees.',
    applicant: 'Telecom Innovations',
    filing_date: '2023-09-15',
    status: 'granted',
    classification: 'H04W-28/08',
    citations_count: 89,
    similarity_score: 0.77,
    related_patents: ['p5', 'p10'],
    category: 'Telecommunications',
  },
  {
    id: 'p10',
    patent_number: 'US-11345678',
    title: 'Homomorphic Encryption for Cloud Computing',
    abstract: 'A fully homomorphic encryption scheme enabling computation on encrypted data without decryption, preserving privacy in cloud environments.',
    applicant: 'CryptoCloud Systems',
    filing_date: '2023-10-30',
    status: 'rejected',
    classification: 'H04L-9/00',
    citations_count: 31,
    similarity_score: 0.71,
    related_patents: ['p6', 'p8'],
    category: 'Cryptography',
  },
  {
    id: 'p11',
    patent_number: 'US-11456789',
    title: 'Computer Vision for Medical Imaging Diagnostics',
    abstract: 'A multi-modal computer vision system for automated medical image analysis with explainable AI for clinical decision support.',
    applicant: 'MedVision Technologies',
    filing_date: '2023-11-08',
    status: 'granted',
    classification: 'G06T-7/00',
    citations_count: 156,
    similarity_score: 0.90,
    related_patents: ['p1', 'p7'],
    category: 'Healthcare AI',
  },
  {
    id: 'p12',
    patent_number: 'US-11567890',
    title: 'Swarm Intelligence for Drone Coordination',
    abstract: 'A bio-inspired swarm intelligence algorithm for coordinating autonomous drone fleets with collision avoidance and task allocation.',
    applicant: 'AeroSwarm Dynamics',
    filing_date: '2023-12-01',
    status: 'pending',
    classification: 'G05D-1/00',
    citations_count: 62,
    similarity_score: 0.80,
    related_patents: ['p3', 'p9'],
    category: 'Robotics',
  },
];

export const suggestedQuestions = [
  'Which patents have the highest similarity scores?',
  'What are the most cited patents in this dataset?',
  'Show me patents related to AI and Machine Learning',
  'Which patents are still pending approval?',
  'What technology areas show the most innovation?',
  'Analyze the relationship between quantum and AI patents',
];
